# docker-compose.yml

services:
  web:
    build:
      # build from Dockerfile
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: movie123
    ports:
      - "3306:3306"
